name: 'SNOWFLAKE_DBT_SAMPLE_PROJECT'
version: '1.0.0'
config-version: 2

profile: 'default'

# Project structure
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where dbt stores compiled SQL and artifacts
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Model configurations
models:
  +persist_docs:
    relation: true
    columns: true

  SNOWFLAKE_DBT_SAMPLE_PROJECT:
    staging:
      +materialized: table
      +database: "{{ env_var('DBT_DATABASE') }}"
      +schema: "{{ env_var('DBT_STAGE_SCHEMA', 'STAGE') }}"

    marts:
      +materialized: table
      +database: "{{ env_var('DBT_DATABASE') }}"
      +schema: "{{ env_var('DBT_MART_SCHEMA', 'MART') }}"
