name: 'snowflake_dbt_sample_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]  

target-path: "target"  # ✅ fixed
clean-targets:
  - "target"
  - "dbt_packages"

models:
  snowflake_dbt_sample_project:
    example:
      +materialized: table
