name: 'SNOWFLAKE_DBT_SAMPLE_PROJECT'
version: '1.0.0'
config-version: 2

profile: 'default'

# Project structure
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_modules"

# Model configurations
models:
  +persist_docs:
    relation: true
    columns: true

  SNOWFLAKE_DBT_SAMPLE_PROJECT:

    staging:
      +materialized: table
      +database: "MY_DBT"
      +schema: "MY_SCHEMA"

    marts:
      +materialized: table
      +database: "MY_DBT"
      +schema: "MY_SCHEMA"

    raw:
      +materialized: table
      +database: "MY_DBT"
      +schema: "public"

flags:
  require_generic_test_arguments_property: true