version: 2

models:
  - name: orders_incremental
    description: "this is for the incremental model testing"
    columns:
      - name: order_id
        description: "Unique identifier for each order. Primary key in the orders table."
      - name: customer_name
        description: "Foreign key reference to the customer who placed the order."
      