{{ config(materialized='table') }}

SELECT
    POLICY_ID,
    CUSTOMER_ID,
    PREMIUM_AMOUNT,
    CLAIM_AMOUNT,
    PAYMENT_STATUS,
    POLICY_STATE,
    PRODUCT_TYPE,
    REPORTING_DATE,
    UPDATED_AT
FROM DEVELOP_SAMPLE_DBT_SNOWFLAKE_PROJECT.PUBLIC.POLICY_FINANCE_RAW